name: habitt
description: "Habitt - A mobile habit tracking app built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3          # Local storage (persistence)
  http: ^1.2.1                        # External API integration
  flutter_local_notifications: ^17.1.2 # Local notifications
  timezone: ^0.9.3                    # Scheduling notification times
  intl: ^0.19.0                       # Time formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
